OEL-94: Finalize ingestion
ec-europa/oe-europa-search-client pull request #39
Opened 2021-05-24 11:42 UTC by claudiu-cristea

2021-05-24 21:09 UTC, drishu requested changes
Let's discuss

2021-05-24 21:09 UTC, drishu commented on src/Api/FileIngestionApi.php
> +            $parts['file'] = $this->jsonEncoder->encode($file, 'json');
If I set a binary string it complains about Malformed UTF-8 characters, I think we don't need to encode at all.

Also in ApiBase::getRequestBody, we always set `'Content-Type' => 'application/json'`, might be we need to adapt, only actual tests will tell.

2021-05-24 21:09 UTC, drishu commented on src/Api/FileIngestionApi.php
> +use OpenEuropa\EuropaSearchClient\Model\Ingestion;
unused, same for TextIngestionApi

2021-05-24 21:09 UTC, drishu commented on src/Api/IngestionApiBase.php
> +            $query['reference'] = $this->jsonEncoder->encode($reference, 'json');
if the purpose is to encode we should use:
```suggestion
            $query['reference'] = rawurlencode($reference);
```
with json encode we will get double quoted strings like ""ref1""

2021-05-24 21:09 UTC, drishu commented on tests/src/Api/FileIngestionApiTest.php
> +            ->ingestFile('http://example.com', chr(0) . 'saDD*&6778)(&88');
Would it be worth here passing the binary of a real file (adding one in a fixtures folders and then file_get_contents..) ?

2021-05-24 21:09 UTC, drishu commented on tests/src/ClientTest.php
> +        $this->assertInstanceOf(TokenAwareInterface::class, $container->get('fileIngestion'));
Lets add one more line to test FileIngestionApiInterface
```
        $this->assertInstanceOf(FileIngestionApiInterface::class, $container->get('fileIngestion'));
```
same for text and delete

2021-05-25 06:38 UTC, claudiu-cristea commented on src/Api/IngestionApiBase.php
> +            $query['reference'] = $this->jsonEncoder->encode($reference, 'json');
We need to pass the raw reference. It's already encoded in `ApiBase::getRequestUri()`.

2021-05-25 10:09 UTC, drishu approved these changes

2021-05-25 10:11 UTC, merged