OEL-291: ESC testing fixes
ec-europa/oe-europa-search-client pull request #52
Opened 2021-07-08 15:10 UTC by abel-santos-corral

List of issues resolved with this PR:
- Remove EuropaSearchApiInvalid from class name (component EuropaSearchApiInvalidParameterValueException).
- Rename inspectRequest to assertRequest in DeleteApiTest component.
- Remove @covers from TokenApiTest component, leave only the class annotation in the top of the class so all methods get parsed.
- Eliminate leftover at FacetApiTest component.
- Move json responses into fixtures, at SearchApiTest.
- Remove the tuple from FacetTestGeneratorTrait and related components.
- Remove the boundry from property and pass it along to methods that use it.

2021-07-12 09:09 UTC, drishu requested changes

2021-07-12 09:09 UTC, drishu commented on src/Api/ApiBase.php
> +use OpenEuropa\EuropaSearchClient\Exception\StatusCodeException;
dont forget to remove it also from the send() method

2021-07-12 09:09 UTC, drishu commented on tests/src/Api/FacetApiTest.php
>      public function inspectRequest(RequestInterface $request): void
Normally this should be assertRequest but OEL-300 might change this anyway.

2021-07-12 09:09 UTC, drishu commented on tests/src/Api/TokenApiTest.php
> -     * @covers ::getToken
you need to do this in all files

2021-07-12 09:09 UTC, drishu commented on tests/src/Api/SearchApiTest.php
> +                    new Response(200, [], file_get_contents(__DIR__ . '/../../fixtures/files/simple_search_response.json'))
we need fixtures for all responses

2021-07-12 09:09 UTC, drishu commented on tests/src/Traits/FacetTestGeneratorTrait.php
> +    protected function generateTestingFacetValuesAsObject(array $facetValuesAsArray): array
this doesn't generate anything, the ticket desc was "generateTestingFacetValuesAsObject (will call the first and convert)", then the name would have been ok, like this its also ok, but then the name needs to be convertTestingFacetValuesToObject

2021-07-12 09:09 UTC, drishu commented on tests/src/Traits/InspectTestRequestTrait.php
> +    protected function inspectBoundary(RequestInterface $request, string $boundary): void
Since this only asserts now lets call it assertBoundary

2021-07-14 07:03 UTC, vintimpe commented on src/Api/ApiBase.php
> +use OpenEuropa\EuropaSearchClient\Exception\StatusCodeException;
done (changed to InvalidStatusCodeException)

2021-07-14 07:06 UTC, vintimpe commented on tests/src/Api/TokenApiTest.php
> -     * @covers ::getToken
all tags removed.

2021-07-15 12:57 UTC, drishu requested changes

2021-07-15 12:57 UTC, drishu commented on tests/src/Api/DeleteApiTest.php
> +    public function assertRequest(RequestInterface $request): void
revert this change for now, it will be fixed in the middleware changes but for now lets be consistent

2021-07-15 12:57 UTC, drishu commented on tests/fixtures/files/delete_document_jwt_response.json
> +{
Lets call the folder tests/fixtures/json

2021-07-15 12:57 UTC, drishu commented on tests/fixtures/files/ingestion_jwt_response.json
> +{
lets use just one json for the tokens, we will add another only when we want a different response.

2021-07-15 12:57 UTC, drishu commented on tests/src/Api/ApiBaseTest.php
> + * Tests the base API.
the class covers we leave in, same for the other ones

2021-07-15 12:57 UTC, drishu commented on tests/src/Api/ApiBaseTest.php
> +     * Tests config resolver.
no comment needed, same below

2021-07-19 16:03 UTC, claudiu-cristea commented
As a _rule of thumb_, don't mark as resolved a remark made by a reviewer unless you're a reviewer too. Normally, a reviewer adds remarks, the developer is fixing them. Then, on 2nd review, the reviewer is checking whether his/her remarks were fixed and mark the fixed ones as _resolved_.

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Model/DocumentTest.php
>   * @covers \OpenEuropa\EuropaSearchClient\Model\Document
Let's use `@coversDefaultClass`

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Model/QueryLanguageTest.php
>   * @covers \OpenEuropa\EuropaSearchClient\Model\QueryLanguage
Let's use `@coversDefaultClass`

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Model/IngestionTest.php
>   * @covers \OpenEuropa\EuropaSearchClient\Model\Ingestion
Let's use `@coversDefaultClass`

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Traits/FacetTestGeneratorTrait.php
>          $facetValuesAsObject = array_map(
This local variable is redundant.

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Traits/FacetTestGeneratorTrait.php
> +    protected function generateTestingFacetValuesAsArray(int $count): array
We should do the same with `::generateTestingFacetItems()`

2021-07-19 17:02 UTC, claudiu-cristea commented on tests/src/Traits/FacetTestGeneratorTrait.php
> +     * @return array
Yes, it's an array but even more: `FacetValue[]`

2021-07-19 17:25 UTC, drishu requested changes

2021-07-19 17:25 UTC, drishu commented on tests/src/Model/MetadataTest.php
> +     * Tests the serialization.
No need for this comment

2021-07-19 17:25 UTC, drishu commented on tests/src/Model/MetadataTest.php
> +     * Tests the invalid offset.
no need for this comment

2021-07-19 17:28 UTC, merged