EWPP-2629: Support for multifield sorting.
ec-europa/oe-europa-search-client pull request #66
Opened 2022-09-21 12:00 UTC by hernani

2022-09-23 15:03 UTC, brummbar requested changes

2022-09-23 15:03 UTC, brummbar commented on src/Contract/ClientInterface.php
>       * @param string|null $sortOrder
We should add a line here that this must be null if sortField is array.

2022-09-23 15:03 UTC, brummbar commented on src/Contract/ClientInterface.php
> +     *   If single field name is used, the $sortOrder parameter is used.
Maybe this line we can drop it by explaining in the next parameter.

2022-09-23 15:03 UTC, brummbar commented on src/Client.php
> +            foreach ($sortField as $field => $order) {
We shouldn't use associative, there might be cases that end up clashing, or when we have expressions/scripts as sorting. I think it's better to go for [$field, $order] with a numeric key. Basically each group of parameters is the arguments for the Sort class.

2022-09-26 12:50 UTC, brummbar requested changes

2022-09-26 12:50 UTC, brummbar commented on src/Client.php
> +                $sort[] = new Sort($sorting_expression[0], $sorting_expression[1]);
```suggestion
                $sort[] = new Sort(...$sorting_expression);
```

2022-09-26 12:50 UTC, brummbar commented on src/Client.php
> +        if (is_array($sortField) && is_null($sortOrder)) {
I realised that here, at this point if $sortField is array $sortOrder will be null as the previous check has asserted that. So we can just check if $sortField is array.

2022-09-26 15:39 UTC, sergepavle commented on src/Endpoint/SearchEndpoint.php
> +    public function getSort(): array
As I understand it can be empty.
```suggestion
    public function getSort(): ?array
```

2022-09-26 15:39 UTC, sergepavle commented on tests/src/Endpoint/SearchEndpointTest.php
> +        $actualResult = $this->getTestingClient($clientConfig, $responses)
Not necessary to have additional variable.
```suggestion
        $this->getTestingClient($clientConfig, $responses)
```

2022-09-26 15:39 UTC, sergepavle commented on tests/src/Endpoint/SearchEndpointTest.php
> +    public function testWrongSearchParameters(array $clientConfig, array $responses, $expectedResult): void
It probably would be nice to have a test for an empty sort.

2022-09-26 17:01 UTC, sergepavle approved these changes

2022-09-27 09:00 UTC, brummbar approved these changes

2022-09-27 09:01 UTC, merged